version: "3.9"

services:
  stereothermal:
    image: stereothermal:latest
    container_name: stereothermal_dev
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/app         # Monta tu proyecto actual dentro del contenedor
    working_dir: /app  # Asegura que el código corra desde la raíz del proyecto
    command: python main.py
